In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import spacy
nlp = spacy.load('en')

import urllib.request
import urllib.parse

from bs4 import BeautifulSoup

torch.cuda.is_available()

True

In [2]:
def prepare_sequence(seq, to_ix):
    idxs = [to_ix[w] for w in seq]
    return torch.tensor(idxs, dtype=torch.long).cuda()

In [3]:
def prepare_lable(size,lable):
    temp = []
    for i in range(size -1):
        temp += [0]   
    if lable == 1:
        temp += [1]
    else:
        temp += [0]
    
    return torch.tensor(temp, dtype=torch.long).cuda()

In [4]:
def get_pos(sentence):
    temp=[]
    doc = nlp(sentence)
    for i in range(len(doc)):
        #temp += [doc[i].tag_]
        temp += [doc[i].pos_]
    return temp

In [5]:
abstr_id = 30252254
train = ''
for i in range(100):
    url = 'https://www.ncbi.nlm.nih.gov/pubmed/'+str(abstr_id)
    html = urllib.request.urlopen(url)
    parsed_html = BeautifulSoup(html)
    if parsed_html is not None:
        train += parsed_html.body.find('div', attrs={'class':'abstr'}).find('p').text 
    #train += '.'


C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file C:\ProgramData\Anaconda3\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
Cockayne syndrome, first described in 1936 by Dr. Cockayne, is a rare genetic disorder, mainly characterized by growth disorders, intellectual deficit, neuromotor difficulties, and impaired vision and hearing. The children look cachectic with a prematurely aged face. There are different types of the syndrome. They depend on the age at which the disease manifests itself and the severity of the manifestations: Type 1 is also called "classical form." It usually occurs at 1 year of age by stunting and neurological disorders, followed by a decline in vision and hearing. Type 2 is a severe form of the syndrome. Neurological disorders and some ocular abnormalities are present from the outset at birth. Type 3

In [6]:
train_sentence = train.split('.',train.count('.'))
counter = 0
print("train_sentence : " + str(len(train_sentence)))
print("--------------------------------------------------------------------------------------")
for p in train_sentence:
    if p is "":
        train_sentence.remove("")
    else:
        print("index : "+str(counter))
        counter+=1
        print (p)
        print("--------------------------------------------------------------------------------------")

train_sentence : 920
--------------------------------------------------------------------------------------
index : 0
Cockayne syndrome, first described in 1936 by Dr
--------------------------------------------------------------------------------------
index : 1
 Cockayne, is a rare genetic disorder, mainly characterized by growth disorders, intellectual deficit, neuromotor difficulties, and impaired vision and hearing
--------------------------------------------------------------------------------------
index : 2
 The children look cachectic with a prematurely aged face
--------------------------------------------------------------------------------------
index : 3
 There are different types of the syndrome
--------------------------------------------------------------------------------------
index : 4
 They depend on the age at which the disease manifests itself and the severity of the manifestations: Type 1 is also called "classical form
--------------------------------------------

--------------------------------------------------------------------------------------
index : 80
 Recently, technological advancement in medical imaging and histological processing has helped practitioners have a better understanding of these lesions
--------------------------------------------------------------------------------------
index : 81
 Further subgroups have since then been identified
--------------------------------------------------------------------------------------
index : 82
 Vascular tumors include hemangiomas, tufted angiomas, pyogenic granulomas, and hemangiopericytomas
--------------------------------------------------------------------------------------
index : 83
 Vascular malformations are further subdivided into the categories of lymphatic, venous, mixed, arteriovenous, or capillary
--------------------------------------------------------------------------------------
index : 84
 Treatment and prognosis of these lesions depend on proper identification as mult

index : 155
 Opioids are the group of drugs used for management of severe pain
--------------------------------------------------------------------------------------
index : 156
 They are also commonly used as psychoactive substances around the world
--------------------------------------------------------------------------------------
index : 157
 Opioids include drugs such as morphine, heroin, oxycontin, codeine, methadone, and hydromorphone hydrochloride
--------------------------------------------------------------------------------------
index : 158
 They produce mental relaxation, pain relief, and euphoric feelings
--------------------------------------------------------------------------------------
index : 159
[1] Chronic use of opioids leads to the development of incapacitating form of dependence in users
--------------------------------------------------------------------------------------
index : 160
[1] Opioid dependence not only impacts the drug user, but also imposes a si

 Median survival in the United States and Jamaica is 45 to 55 years
--------------------------------------------------------------------------------------
index : 229
 [2] Natural history by age in SCD is as follows: Newborn babies are asymptomatic for an initial couple of months, given fetal Hb (HbF) predominance
--------------------------------------------------------------------------------------
index : 230
 Early childhood is characterized by episodes of dactylitis, acute chest syndrome (ACS), sepsis, splenic sequestration, and stroke
--------------------------------------------------------------------------------------
index : 231
 Human parvovirus B19 infection can lead to severe and sudden anemia in children and adolescents with SCD as the virus destroys precursors of the red blood cells
--------------------------------------------------------------------------------------
index : 232
 After age 5: Classic painful vaso-occlusive crisis (VOC), which increases in frequency with a

 The following timing of embryological developments, with particular attention to the CNS, offer a greater understanding of the process
--------------------------------------------------------------------------------------
index : 303
 Weeks 1 to 3: Zygote formation, blastocyst, and gastrulation occur
--------------------------------------------------------------------------------------
index : 304
 Mid-fourth week: Embryo is linear and uniform; notochord formation occurs
--------------------------------------------------------------------------------------
index : 305
 Late-fourth week: Many forms of differential growth occur; upper limb buds always develop before the lower limb bud
--------------------------------------------------------------------------------------
index : 306
 Fifth week: Limb buds more pronounced
--------------------------------------------------------------------------------------
index : 307
 Sixth week: Can begin to see eyes and auricular hillocks, which will 

--------------------------------------------------------------------------------------
index : 375
 The medial terminal branch accompanies the dorsalis pedis and runs on the dorsum of the foot reaching the first interosseous space where it divides into digital nerves that supply the side of the great and second toes
--------------------------------------------------------------------------------------
index : 376
 The lateral terminal branch runs beneath the extensor digitorum brevis and gives off interosseous branches that supply the tarsal and metatarsophalangeal joints
--------------------------------------------------------------------------------------
index : 377
[1]Renal involvement in lymphoma is commonly in the presence of widespread nodal or extranodal lymphoma
--------------------------------------------------------------------------------------
index : 378
 This is classified as secondary renal lymphoma (SRL)
-----------------------------------------------------------------

--------------------------------------------------------------------------------------
index : 444
Isoproterenol is indicated for the following: The fascia in the foot is composed of fibrous connective tissue that serves to separate, support, and attach muscles
--------------------------------------------------------------------------------------
index : 445
 It can be divided into the superficial fascia and the deep fascia
--------------------------------------------------------------------------------------
index : 446
 The superficial fascia is located just beneath the skin and varies in strength depending on where it is in the foot
--------------------------------------------------------------------------------------
index : 447
 On the dorsal side of the foot, the superficial fascia is thin and mobile
--------------------------------------------------------------------------------------
index : 448
 In contrast, the superficial fascia of the plantar side is thick and has multiple 

 In some circumstances, this process does not go as expected, and healing does not occur without additional intervention
--------------------------------------------------------------------------------------
index : 519
 Definitions vary among different studies, but overall, a diagnosis can be made when there is no evidence of progression of the healing process for 3 months or no healing after 9 months of the injury
--------------------------------------------------------------------------------------
index : 520
[1][2][3][4] This condition will not only have a detrimental effect on the patient’s quality of life, comparable to advanced hip arthrosis and worse than congestive heart failure; but it also has a high impact on the total care costs, double the cost of fractures that heal adequately
--------------------------------------------------------------------------------------
index : 521
 Despite the different options available, treatment of tibial nonunions still is challenging for 

 Other locations (atypical/secondary fissures) can be caused by other underlying conditions that require further workup
--------------------------------------------------------------------------------------
index : 640
 The diagnosis of anal fissure is primarily clinical
--------------------------------------------------------------------------------------
index : 641
 Several treatment options exist, including medical management and surgical options
--------------------------------------------------------------------------------------
index : 642
Sickle cell disease (SCD) is a group of inherited red blood cell disorders affecting about 1 in 500 African American children and 1 in 36,000 Hispanic American children
--------------------------------------------------------------------------------------
index : 643
[1] SCD results in anemia and "sickle cell crisis" (SCC)
--------------------------------------------------------------------------------------
index : 644
 The main clinical fea

 At birth, the xiphoid is pure cartilage
--------------------------------------------------------------------------------------
index : 795
 The xiphoid process is made up of 2 types of cartilage
--------------------------------------------------------------------------------------
index : 796
 It contains hyaline cartilage in the proximal portion and contains elastic cartilage in the distal portion
--------------------------------------------------------------------------------------
index : 797
[2] As humans age, the xiphoid process ossifies, although there are variations in when this process begins
--------------------------------------------------------------------------------------
index : 798
[1]Research confirms interviewing is an effective system of gathering essential information regarding the personality and character of another person
--------------------------------------------------------------------------------------
index : 799
 In the medical profession, interviews are 

In [7]:
#for 20
# train_target = [1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
#                 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
train_target=[]

for i in range(len(train_sentence)):
    train_target += [1]
need_to_change=[0,1,4,5,30,31,32,33,34,50,51,52,53,54,55,56,57,58,59,60,61,62,100,101,103,104,129,130,131,132,133,161,162,163,165,166,174,175
               ,187,188,189,190,201,202,209,210,216,217,266,267,290,294,297,383,384,463,464,466,467,468,469,470,471,472,542,544,546,548,550
               ,622,623,680,681,682,731,732,733,734,735,736,737,738,740,741,828,829,830,831,833,834,856,857]
#need_to_change=[0,1,4,5]
for i in need_to_change:
    train_target[i] = 0
print(train_target)

In [8]:
training_data=[]
for i in range(len(train_sentence)):
    training_data+=[ (get_pos(train_sentence[i]), train_target[i]) ]
print(training_data)

[(['PROPN', 'NOUN', 'PUNCT', 'ADV', 'VERB', 'ADP', 'NUM', 'ADP', 'PROPN'], 0), (['SPACE', 'PROPN', 'PUNCT', 'VERB', 'DET', 'ADJ', 'ADJ', 'NOUN', 'PUNCT', 'ADV', 'VERB', 'ADP', 'NOUN', 'NOUN', 'PUNCT', 'ADJ', 'NOUN', 'PUNCT', 'NOUN', 'NOUN', 'PUNCT', 'CCONJ', 'ADJ', 'NOUN', 'CCONJ', 'NOUN'], 0), (['SPACE', 'DET', 'NOUN', 'VERB', 'ADJ', 'ADP', 'DET', 'ADV', 'ADJ', 'NOUN'], 1), (['SPACE', 'ADV', 'VERB', 'ADJ', 'NOUN', 'ADP', 'SPACE', 'DET', 'NOUN'], 1), (['SPACE', 'PRON', 'VERB', 'ADP', 'DET', 'NOUN', 'ADP', 'ADJ', 'DET', 'NOUN', 'VERB', 'PRON', 'CCONJ', 'DET', 'NOUN', 'ADP', 'DET', 'NOUN', 'PUNCT', 'NOUN', 'NUM', 'VERB', 'ADV', 'VERB', 'PUNCT', 'ADJ', 'NOUN'], 0), (['PUNCT', 'PRON', 'ADV', 'VERB', 'ADP', 'NUM', 'NOUN', 'ADP', 'NOUN', 'ADP', 'VERB', 'CCONJ', 'ADJ', 'NOUN', 'PUNCT', 'VERB', 'ADP', 'DET', 'NOUN', 'ADP', 'NOUN', 'CCONJ', 'NOUN'], 0), (['SPACE', 'NOUN', 'NUM', 'VERB', 'DET', 'ADJ', 'NOUN', 'ADP', 'DET', 'NOUN'], 1), (['SPACE', 'ADJ', 'NOUN', 'CCONJ', 'DET', 'ADJ', 'NOUN', 'VE

In [9]:
# import csv
# training_data=[]
# with open('data/test4.csv', newline='') as csvfile:
#     rows = csv.reader(csvfile)
#     for row in rows:
#         training_data+=[ (get_pos(row[0]), int(row[1])) ]
   
# print(len(training_data))
# print(training_data)

In [10]:
# word_to_ix = {}
# for sent, tags in training_data:
#     for word in sent:
#         if word not in word_to_ix:
#             word_to_ix[word] = len(word_to_ix)
# print(word_to_ix)
word_to_ix = {'SPACE': 0, 'ADP':1, 'ADV':2, 'AUX':3, 'CONJ':4, 'CCONJ':5, 'DET':6, 'INTJ':7, 'NUM':8, 'PART':9, 'PRON':10,
              'PROPN':11, 'PUNCT':12, 'SCONJ':13, 'SYM':14, 'VERB':15, 'NOUN':16, 'X':17, 'ADJ': 18 }

print(prepare_sequence(training_data[0][0], word_to_ix))
print(prepare_lable(len(training_data[0][0]),training_data[0][1]))
print(prepare_sequence(training_data[1][0], word_to_ix))
print(prepare_lable(len(training_data[1][0]),training_data[1][1]))

tensor([11, 16, 12,  2, 15,  1,  8,  1, 11], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([ 0, 11, 12, 15,  6, 18, 18, 16, 12,  2, 15,  1, 16, 16, 12, 18, 16, 12,
        16, 16, 12,  5, 18, 16,  5, 16], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0], device='cuda:0')


In [11]:
class LSTMTagger(nn.Module):

    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init__()
        self.hidden_dim = hidden_dim

        self.word_embeddings = nn.Embedding(vocab_size, embedding_dim)

        # The LSTM takes word embeddings as inputs, and outputs hidden states
        # with dimensionality hidden_dim.
        self.lstm = nn.LSTM(embedding_dim, hidden_dim)

        # The linear layer that maps from hidden state space to tag space
        self.hidden2tag = nn.Linear(hidden_dim, tagset_size)
        self.hidden = self.init_hidden()
        
    def init_hidden(self):
        # Before we've done anything, we dont have any hidden state.
        # Refer to the Pytorch documentation to see exactly
        # why they have this dimensionality.
        # The axes semantics are (num_layers, minibatch_size, hidden_dim)
        return (torch.zeros(1, 1, self.hidden_dim).cuda(),
                torch.zeros(1, 1, self.hidden_dim).cuda())

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm( embeds.view(len(sentence), 1, -1), self.hidden)
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space,dim=1)
        return tag_scores

In [12]:
EMBEDDING_DIM = 10
HIDDEN_DIM = 10

model = LSTMTagger(EMBEDDING_DIM, HIDDEN_DIM, len(word_to_ix), 2)
loss_function = nn.NLLLoss()
optimizer = optim.Adam(model.parameters(), lr=0.3)

model = model.cuda()
loss_function = loss_function.cuda()


for epoch in range(5000):  # again, normally you would NOT do 300 epochs, it is toy data
    for sentence, lable in training_data:
        # Step 1. Remember that Pytorch accumulates gradients.
        # We need to clear them out before each instance
        model.zero_grad()
 
        # Also, we need to clear out the hidden state of the LSTM,
        # detaching it from its history on the last instance.
        model.hidden = model.init_hidden()

        # Step 2. Get our inputs ready for the network, that is, turzn them into
        # Tensors of word indices.
        sentence_in = prepare_sequence(sentence, word_to_ix)
        targets = lable

        
        # Step 3. Run our forward pass.
        tag_scores = model(sentence_in)
        #print (tag_scores)
        #print (tag_scores[-1])
        tag_scores = tag_scores[-1].view(1,-1)

        # Step 4. Compute the loss, gradients, and update the parameters by
        #  calling optimizer.step()
        loss = loss_function(tag_scores, torch.LongTensor([targets]).cuda())
        loss.backward()
        optimizer.step()
       
    print(epoch)
     

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

3498
3499
3500
3501
3502
3503
3504
3505
3506
3507
3508
3509
3510
3511
3512
3513
3514
3515
3516
3517
3518
3519
3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697


In [13]:
import numpy as np
def get_consequence(output):
    output = output.cpu()
    x = output.data.numpy()[-1,0]
    y = output.data.numpy()[-1,1]
    
    if x < y :
        print(x,y)
        print("yes(100%)")
    else:
        print(x,y)
        if y > -5:
            print("yes(50%)")
        else:
            print("not")

In [14]:
inputs = prepare_sequence(get_pos("It is an apple"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)
print(tag_scores)

-6.639143 -0.001308918
yes(100%)
tensor([[-20.0008,   0.0000],
        [-30.6364,   0.0000],
        [  0.0000, -24.8598],
        [ -6.6391,  -0.0013]], device='cuda:0', grad_fn=<LogSoftmaxBackward>)


In [15]:
inputs = prepare_sequence(get_pos("The children look cachectic with a prematurely aged face. There are different types of the syndrome"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)

-7.215919 -0.0007350445
yes(100%)


In [16]:
inputs = prepare_sequence(get_pos("Cockayne syndrome, first described in 1936 by Dr"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)

-0.0064721107 -5.043482
not


In [17]:
inputs = prepare_sequence(get_pos("Primary renal lymphoma comprises only 0"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)

0.0 -20.697273
not


In [18]:
inputs = prepare_sequence(get_pos("Ibuprofen, 2-(4-isobutylphenyl)propionic acid, belonging to the class of drugs called nonsteroidal anti-inflammatory drugs (NSAIDs) was discovered by Dr"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)

-0.0064721107 -5.043482
not


In [19]:
# file = open('data/text.txt')
# text = file.read()
# print(text)

In [20]:
abstr_id = 30252110
test=''
j=0
for j in range(2):
    url = 'https://www.ncbi.nlm.nih.gov/pubmed/'+str(abstr_id)
    html = urllib.request.urlopen(url)
    parsed_html = BeautifulSoup(html)
    if parsed_html is not None:
        test += parsed_html.body.find('div', attrs={'class':'abstr'}).find('p').text
    abstr_id+=1
#print(test)

C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file C:\ProgramData\Anaconda3\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


In [22]:
test_sentence = test.split(".",test.count('.'))
for p in test_sentence:
    if p is "":
        test_sentence.remove("")
    else:
        print(p)

Uncertainty in the estimation of daytime ecosystem carbon cycling due to the light inhibition of leaf respiration and photorespiration, and how these small fluxes vary through the growing season in the field, remains a confounding element in calculations of gross primary productivity and ecosystem respiration
 Our study focuses on how phenology, short-term temperature changes and canopy position influence leaf-level carbon exchange in Quercus rubra L
 (red oak) at Harvard Forest in central Massachusetts, USA
 Using leaf measurements and eddy covariance, we also quantify the effect of light inhibition on estimates of daytime respiration at leaf and ecosystem scales
 Measured rates of leaf respiration in the light and dark were highest in the early growing season and declined in response to 10-day prior air temperatures (P < 0
01), evidence of within-season thermal acclimation
 Leaf respiration was significantly inhibited by light (27
1 ± 2
82% inhibited across all measurements), and thi

In [23]:
for t in test_sentence:
    print(t)
    #print(get_pos(t))
    inputs = prepare_sequence(get_pos(t), word_to_ix)
    tag_scores = model(inputs)
    print(inputs)
    get_consequence(tag_scores)
    print("--------------------------------------------------------")

Uncertainty in the estimation of daytime ecosystem carbon cycling due to the light inhibition of leaf respiration and photorespiration, and how these small fluxes vary through the growing season in the field, remains a confounding element in calculations of gross primary productivity and ecosystem respiration
tensor([16,  1,  6, 16,  1, 18, 16, 16, 16,  1,  1,  6, 18, 16,  1, 16, 16,  5,
        16, 12,  5,  2,  6, 18, 16, 15,  1,  6, 15, 16,  1,  6, 16, 12, 15,  6,
        15, 16,  1, 16,  1, 18, 18, 16,  5, 16, 16], device='cuda:0')
-9.214388 -9.9658966e-05
yes(100%)
--------------------------------------------------------
 Our study focuses on how phenology, short-term temperature changes and canopy position influence leaf-level carbon exchange in Quercus rubra L
tensor([ 0, 18, 16, 15,  1,  2, 16, 12, 18, 12, 16, 16, 16,  5, 16, 16, 16, 16,
        12, 16, 16, 16,  1, 11, 16, 16], device='cuda:0')
-7.9692917 -0.00034594536
yes(100%)
-------------------------------------------------

In [32]:
print(model)
print(model.state_dict)
torch.save(model,'./rnn.pkl')
torch.save(model.state_dict,'./rnn_p.pkl')

LSTMTagger(
  (word_embeddings): Embedding(19, 10)
  (lstm): LSTM(10, 10)
  (hidden2tag): Linear(in_features=10, out_features=2, bias=True)
)
<bound method Module.state_dict of LSTMTagger(
  (word_embeddings): Embedding(19, 10)
  (lstm): LSTM(10, 10)
  (hidden2tag): Linear(in_features=10, out_features=2, bias=True)
)>


C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py:241: UserWarning: Couldn't retrieve source code for container of type LSTMTagger. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "


In [ ]:
a = torch.FloatTensor([[1,2,3] , [5,6,7]])
b = torch.FloatTensor([[4,5,6] , [7,8,9]])
c = torch.cat((a,b),1)
c


In [4]:
c[0][1]

tensor(2.)

In [37]:
model5 = LSTMTagger(10, 10, 19, 2)
model5.load_state_dict(torch.load('rnn_p.pkl'))
#model5 = torch.load('rnn.pkl')

AttributeError: 'function' object has no attribute 'copy'